# Generated by Django 6.1 on 2026-09-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_images_created_at_images_user_and_more'),
        ('web', '0002_post_userprofile'),
    ]

    operations = [
    ]
