# Generated by Django 6.1 on 2026-09-04 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_merge_20260904_1442'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='images',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
