# Generated by Django 6.1 on 2026-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_post_latitude_post_location_name_post_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('interknot', 'Interknot'), ('proxy', 'Proxy')], default='interknot', max_length=20),
        ),
    ]
